apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  services.conf:
    ENABLED_SERVICES="{{ range .Values.services.enabled }}{{.}}{{ end }}"
    DISABLED_SERVICES="{{ range .Values.services.disabled }}{{.}}{{ end }}"

  config.yaml: |
    {{ .Values.config | toYaml | indent 4 | trim }}
  
  nftables.conf: |
    {{ .Values.nftables | indent 4 | trim }}
  
  bird.conf: |
    {{ .Values.bird | indent 4 | trim }}
