apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{ .Values.config | toYaml | indent 4 | trim }}
  
{{ .Values.additional_config | toYaml | indent 2 }}