# These are located in a YAML file because they are used across multiple services
# Network config
network:
  replication:
    interface: n-replication
    subnet: 10.168.100.0/24

  dmz:
    interface: n-dmz
    static_mac: "e1:ee:ee:95:c9:f9"
    dhcp_hostname: "router"
    qos: layer-cake.qos
    bandwidth:
      down: 40000
      up: 40000


virtual_ipaddress:
  - 192.168.1.1/24 dev n-home
  - 192.168.2.1/24 dev n-guest

dhcp_helper:
  # DHCP Server Side (upstream)
  upstream:
    addresses:
    - 192.168.1.2
    interfaces: 
    - "n-home"

  # DHCP Clients Side (downstream)
  downstream:
    interfaces:
    - "n-guest"

zerotier:
  api_key: None
  networks: []
