#!/bin/bash
#

# This is the _most_ disgusting script ever.

source /etc/zerotier.conf

# Startup zerotier
if [ "$ZT_API_KEY" == "" ]; then
	echo "ZT_API_KEY is not set."
	exit 1
fi

if [ "$ZT_NETWORKS" == "" ]; then
	echo "ZT_NETWORKS is not set"
	exit 1
fi

# Ensure directory exists
mkdir -p /var/lib/zerotier-one/networks.d/

# Join networks in $ZT_NETWORKS
for i in $ZT_NETWORKS; do
network=$(echo $i | cut -f1 -d=)
address=$(echo $i | cut -f2 -d=)
cat <<EOF > /var/lib/zerotier-one/networks.d/${network}.local.conf
allowManaged=1
allowGlobal=0
allowDefault=0
EOF
touch /var/lib/zerotier-one/networks.d/${network}.conf

done

# Start ZT-one in the background
zerotier-one &
ZTPID=$!
sleep 1

# Wait for an identity
ZT_IDENT=$(zerotier-cli info -j | jq -er '.address')
while [ "$ZT_IDENT" == "" ]; do
    sleep 5
    ZT_IDENT=$(zerotier-cli info -j | jq -er '.address')
done

# Got an identity:
echo "Got an identity: $ZT_IDENT"

# Join networks in $ZT_NETWORKS
for i in $ZT_NETWORKS; do
  network=$(echo $i | cut -f1 -d=)
  address=$(echo $i | cut -f2 -d=)

  # Registered...
  echo "Approving registration..."
  # Approve registration and configure ZeroTier
  POSTDATA='{ "name": "{{HOSTNAME}}", "config": { "authorized": true, "activeBridge": true, "ipAssignments": [ "{{IPADDR}}" ] }, "hidden": false }'
  POSTDATA=$(echo $POSTDATA | sed "s/{{HOSTNAME}}/$(hostname)/" | sed "s/{{IPADDR}}/${address}/")
  false
  # Retry forever logic
  while [ $? -ne 0 ]; do
    curl -Sso /dev/null -XPOST -H "Authorization: bearer $ZT_API_KEY" -d "$POSTDATA" "https://my.zerotier.com/api/network/${network}/member/$ZT_IDENT"
    sleep 5
  done
  if [ $? -eq 0 ]; then
    echo "Registration approved..."
  fi
done


wait $ZTPID
